# Generated by Django 5.0.4 on 2024-07-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cors_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotAppDistrict',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('site_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'plot_app_district',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlotAppPlotData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('site_name', models.TextField(blank=True, null=True)),
                ('site_code', models.TextField(blank=True, null=True)),
                ('image_Cycle_Slip_PLOT', models.ImageField(upload_to='media')),
                ('image_MP_PLOT', models.ImageField(upload_to='media')),
                ('image_Percentage_Observation', models.ImageField(upload_to='media')),
                ('image_TS_PLOT', models.ImageField(upload_to='media')),
                ('coordinates', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'plot_app_plot_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlotAppSitedata',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('corsid', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('site_name', models.CharField(max_length=100)),
                ('site_code', models.CharField(max_length=10)),
                ('coordinates_of_sites_dms_lat', models.CharField(max_length=50)),
                ('coordinates_of_sites_dms_long', models.CharField(max_length=50)),
                ('coordinates_of_sites_dms_elp_height', models.FloatField()),
            ],
            options={
                'db_table': 'plot_app_sitedata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlotAppState',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'plot_app_state',
                'managed': False,
            },
        ),
    ]
